apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o piggymetrics -c
    kompose.service.type: loadbalancer
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o piggymetrics -c
        kompose.service.type: loadbalancer
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "123123"
        image: todotodo/piggymetrics-gateway
        name: gateway
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
