apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o piggymetrics -c
    kompose.service.type: loadbalancer
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: monitoring
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o piggymetrics -c
        kompose.service.type: loadbalancer
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: monitoring
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "123123"
        image: todotodo/piggymetrics-monitoring
        name: monitoring
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
