apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o piggymetrics -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: turbine-stream-service
  name: turbine-stream-service
spec:
  ports:
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    io.kompose.service: turbine-stream-service
status:
  loadBalancer: {}
