apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
        io.kompose.service: redis-master
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-master
    spec:
      containers:
      - image: k8s.gcr.io/redis:e2e
        name: redis-master
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
status: {}
